version: '3.0'
services:
  haste-server:
    build: .
    container_name: paste
    networks:
      - nginx
      - haste-network
    environment:
      - STORAGE_TYPE=redis
      - STORAGE_HOST=haste-redis
      - STORAGE_PORT=6379
    ports:
      - 7777:7777
  haste-redis:
    image: redis:latest
    volumes:
      - haste:/redis
    networks:
      - haste-network

volumes:
  haste:
networks:
  haste-network:
  nginx:
    external: true
    name: nginx
